### ISSUE TITLE
discord.py error

### ISSUE THREAD

**Issue by xSelee** [bmochan/pokefier#1]
its says ;
λ python C:\Users\\Desktop\pokefier-main\autocatcher\poke.py
Traceback (most recent call last):
  File "C:\Users\mone\Desktop\pokefier-main\autocatcher\poke.py", line 7, in <module>
    import discord
  File "C:\Users\\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\__init__.py", line 25, in <module>
    from .client import Client
  File "C:\Users\e\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 53, in <module>
    from .webhook import Webhook
  File "C:\Users\\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\webhook\__init__.py", line 12, in <module>
    from .async_ import *
  File "C:\Users\\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\webhook\async_.py", line 46, in <module>
    from ..http import Route, handle_message_parameters, MultipartParameters, HTTPClient, json_or_text
ImportError: cannot import name 'handle_message_parameters' from 'discord.http' (C:\Users\\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py)

how can i fix it sir

**Comment by xSelee** [comment]
nvm i fixed it

**Comment by ahead1234** [comment]
how did you fixed that tho
